# Generated by Django 3.1.4 on 2020-12-15 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('height', models.FloatField(default=0.0, max_length=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('weight', models.FloatField(default=0.0, max_length=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0.0, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('calories', models.FloatField(default=0.0, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('carbs', models.FloatField(default=0.0, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fat', models.FloatField(default=0.0, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('protein', models.FloatField(default=0.0, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price', models.FloatField(default=0.0, max_length=100, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('portions', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ManyToManyField(null=True, to='api_recipes.Product')),
            ],
        ),
        migrations.CreateModel(
            name='userprofile_recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='list of profiles')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0.0, max_length=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_recipes.recipe')),
            ],
        ),
    ]
