# Generated by Django 3.1.4 on 2020-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0002_auto_20201230_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(null=True, to='api_recipes.Recipe'),
        ),
    ]
