# Generated by Django 3.1.4 on 2020-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0003_auto_20201230_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(to='api_recipes.Recipe'),
        ),
    ]
