# Generated by Django 3.1.4 on 2020-12-30 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0004_auto_20201230_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, max_length=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
