# Generated by Django 3.1.4 on 2020-12-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0005_auto_20201230_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparing_time',
            field=models.CharField(max_length=100),
        ),
    ]
