# Generated by Django 3.1.4 on 2020-12-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0006_auto_20201230_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_link_big',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_link_small',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparing_time',
            field=models.CharField(max_length=1000),
        ),
    ]
