# Generated by Django 3.1.4 on 2021-01-03 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0007_auto_20201231_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0.0, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('calories', models.FloatField(default=0.0, max_length=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('carbs', models.FloatField(default=0.0, max_length=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fat', models.FloatField(default=0.0, max_length=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('protein', models.FloatField(default=0.0, max_length=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price', models.FloatField(default=0.0, max_length=100, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_recipes.ingredient')),
            ],
        ),
    ]
