# Generated by Django 3.1.4 on 2021-01-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
