# Generated by Django 3.1.4 on 2021-01-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0009_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Product',
        ),
    ]
