# Generated by Django 3.1.4 on 2021-01-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0010_auto_20210103_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type_of_ingredient',
            field=models.IntegerField(choices=[(1, 'gram'), (2, 'items'), (3, 'title'), (4, 'table spoon'), (5, 'ml'), (6, 'by taste'), (7, 'tea spoon'), (8, 'little'), (9, 'kg')], null=True),
        ),
    ]
