# Generated by Django 3.1.4 on 2021-01-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_recipes', '0011_ingredient_type_of_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type_of_ingredient',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
